name: app_shortener
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.4.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
  build_runner: ^2.4.0 
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4



flutter:

  uses-material-design: true


